spring.application.name=avarLMS
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/avar_lms
spring.datasource.username=mostafafatayri
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
api.prefix=/api/v1
--------
/*Bucket*/
supabase.s3.access-key=62141214002f2d8dc4ae36868bd6843e
supabase.s3.secret-key=4460886130dc59d7cdd0ecd8505f5df45cfec557f31a9f5dd4
supabase.url=https://kqunjevmxxfukblbeylq.supabase.co
supabase.service-role-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxdW5qZXZteHhmdWtibGJleWxxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTE4NDAwNSwiZXhwIjoyMDk0NzYwMDA1fQ.oG2wZBZYqG0GhMvl3nafmz_U7qLU72AlcHn8o0YiSN4
supabase.bucket=Facility Managment
// mail service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mostafafatayri@gmail.com
spring.mail.password=timj obzo tkxd pmyv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
flowable.database-schema-update=true
flowable.async-executor-activate=true


